add_lunch_combo candykat_amami-userdebug
add_lunch_combo candykat_flo-userdebug
add_lunch_combo candykat_grouper-userdebug
add_lunch_combo candykat_hammerhead-userdebug
add_lunch_combo candykat_m7-userdebug
add_lunch_combo candykat_m7spr-userdebug
add_lunch_combo candykat_m7vzw-userdebug
add_lunch_combo candykat_m8-userdebug
add_lunch_combo candykat_maguro-userdebug
add_lunch_combo candykat_mako-userdebug
add_lunch_combo candykat_toro-userdebug
add_lunch_combo candykat_toroplus-userdebug
add_lunch_combo candykat_ville-userdebug

