add_lunch_combo candy5_d850-userdebug
add_lunch_combo candy5_d851-userdebug
add_lunch_combo candy5_d852-userdebug
add_lunch_combo candy5_d855-userdebug
add_lunch_combo candy5_evita-userdebug
add_lunch_combo candy5_falcon-userdebug
add_lunch_combo candy5_flo-userdebug
add_lunch_combo candy5_flounder-userdebug
add_lunch_combo candy5_grouper-userdebug
add_lunch_combo candy5_hammerhead-userdebug
add_lunch_combo candy5_ls990-userdebug
add_lunch_combo candy5_m7-userdebug
add_lunch_combo candy5_m7spr-userdebug
add_lunch_combo candy5_m7vzw-userdebug
add_lunch_combo candy5_m8-userdebug
add_lunch_combo candy5_mako-userdebug
add_lunch_combo candy5_otterx-userdebug







